using System.Text.Json.Serialization;
using backend.Models;

namespace backend;

[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
[JsonSerializable(typeof(SponsorCompany))]
[JsonSerializable(typeof(ApplicationStage))]
[JsonSerializable(typeof(LoginRequest))]
[JsonSerializable(typeof(LoginResponse))]
[JsonSerializable(typeof(RegisterRequest))]
[JsonSerializable(typeof(UpdateProfileRequest))]
[JsonSerializable(typeof(ChangePasswordRequest))]
[JsonSerializable(typeof(ForgotPasswordRequest))]
[JsonSerializable(typeof(ResetPasswordRequest))]
[JsonSerializable(typeof(ResendVerificationRequest))]
[JsonSerializable(typeof(ChangeEmailRequest))]
[JsonSerializable(typeof(PromoteRequest))]
[JsonSerializable(typeof(BulkStatusRequest))]
[JsonSerializable(typeof(UpdateCompanyRequest))]
[JsonSerializable(typeof(MergeCompaniesRequest))]
[JsonSerializable(typeof(MergeCompaniesResponse))]
[JsonSerializable(typeof(AdminUserSummary))]
[JsonSerializable(typeof(AdminUserSummary[]), TypeInfoPropertyName = "AdminUserSummaryArray")]
[JsonSerializable(typeof(ActivityLog))]
[JsonSerializable(typeof(ActivityLog[]), TypeInfoPropertyName = "ActivityLogArray")]
[JsonSerializable(typeof(StatusHistory))]
[JsonSerializable(typeof(StatusHistory[]), TypeInfoPropertyName = "StatusHistoryArray")]
[JsonSerializable(typeof(AddStatusHistoryRequest))]
[JsonSerializable(typeof(UpdateStatusHistoryRequest))]
[JsonSerializable(typeof(ParseJobLinkRequest))]
[JsonSerializable(typeof(ParseJobLinkResponse))]
[JsonSerializable(typeof(CompanyListsResponse))]
[JsonSerializable(typeof(SetCompanyListRequest))]
[JsonSerializable(typeof(MessageResponse))]
[JsonSerializable(typeof(EnrichResponse))]
[JsonSerializable(typeof(ResendEmailRequest))]
[JsonSerializable(typeof(ErrorResponse))]
[JsonSerializable(typeof(JwtPayload))]
[JsonSerializable(typeof(PreferencesPayload))]
[JsonSerializable(typeof(SponsorCompany[]))]
[JsonSerializable(typeof(ApplicationStage[]))]
[JsonSerializable(typeof(StatsResponse))]
[JsonSerializable(typeof(StatusFlowResponse))]
[JsonSerializable(typeof(Dictionary<string, int>))]
[JsonSerializable(typeof(string[]))]
[JsonSerializable(typeof(SyncLog))]
[JsonSerializable(typeof(SyncLog[]), TypeInfoPropertyName = "SyncLogArray")]
internal partial class AppJsonSerializerContext : JsonSerializerContext
{
}
