<template>
  <div class="privacy-page">
    <div class="privacy-card">
      <h1 class="privacy-title">Privacy Policy</h1>
      <p class="privacy-updated">Last updated: June 2026</p>

      <section class="privacy-section">
        <h2 class="section-heading">What this tool is</h2>
        <p>
          <em>ik wil werk zoeken</em> ("IWWZ") is a personal job-search tracker for Highly Skilled
          Migrants in the Netherlands. It is a private tool — not a commercial service.
        </p>
      </section>

      <section class="privacy-section">
        <h2 class="section-heading">What data we collect and why</h2>
        <table class="data-table">
          <thead>
            <tr><th>Data</th><th>Why</th></tr>
          </thead>
          <tbody>
            <tr><td>Email address</td><td>Account login and password-reset emails</td></tr>
            <tr><td>First and last name</td><td>Displayed in your profile</td></tr>
            <tr><td>Password (hashed)</td><td>Authentication — stored as a PBKDF2-SHA256 hash, never in plain text</td></tr>
            <tr><td>Job preferences (target role, location, work type)</td><td>Shown in your profile; never shared</td></tr>
            <tr><td>Application records (company, position, status, notes)</td><td>Core feature — your private job pipeline</td></tr>
            <tr><td>GDPR consent timestamp</td><td>Legal record of your consent at registration</td></tr>
          </tbody>
        </table>
        <p class="privacy-note">
          We collect only what is needed to run the tool. No analytics, no tracking pixels,
          no advertising data.
        </p>
      </section>

      <section class="privacy-section">
        <h2 class="section-heading">Where data is stored</h2>
        <p>
          All data is stored in a PostgreSQL database hosted on
          <strong>Microsoft Azure</strong> (West Europe region). Session tokens are stored only
          in your browser's <code>sessionStorage</code> and are cleared when you close the tab.
        </p>
      </section>

      <section class="privacy-section">
        <h2 class="section-heading">AI-generated content (Google Gemini)</h2>
        <p>
          Company summaries displayed in the <em>Companies</em> tab are generated by
          <strong>Google Gemini</strong> (a third-party AI service). When the monthly IND
          sponsor sync runs, company names and KvK numbers are sent to the Gemini API to
          generate short descriptions. These summaries may contain errors or inaccuracies —
          always verify with official sources.
        </p>
        <p>
          <strong>Your personal data is never sent to Gemini.</strong> Only public company
          information (name, KvK number) is used.
        </p>
        <p>
          Google's data processing terms apply to these API calls:
          <a href="https://ai.google.dev/terms" target="_blank" rel="noopener" class="privacy-link">ai.google.dev/terms</a>.
        </p>
      </section>

      <section class="privacy-section">
        <h2 class="section-heading">Password reset emails</h2>
        <p>
          If you request a password reset, your email address is passed to
          <strong>Resend</strong> (a transactional email service) to deliver the reset link.
          Resend's privacy policy applies: <a href="https://resend.com/legal/privacy-policy" target="_blank" rel="noopener" class="privacy-link">resend.com/legal/privacy-policy</a>.
        </p>
      </section>

      <section class="privacy-section">
        <h2 class="section-heading">Your rights (GDPR)</h2>
        <ul class="privacy-list">
          <li><strong>Right of access</strong> — all your data is visible in the app.</li>
          <li><strong>Right to rectification</strong> — edit your profile and application records at any time.</li>
          <li>
            <strong>Right to erasure</strong> — go to <em>Profile → Danger Zone → Delete account</em>.
            This permanently deletes your account and all associated data from the database.
          </li>
          <li><strong>Right to portability</strong> — contact us to request a data export.</li>
        </ul>
      </section>

      <section class="privacy-section">
        <h2 class="section-heading">Contact</h2>
        <p>
          Questions or data requests: <a href="mailto:atainogoibaev@gmail.com" class="privacy-link">atainogoibaev@gmail.com</a>
        </p>
      </section>
    </div>
  </div>
</template>

<style scoped>
.privacy-page {
  min-height: 100vh;
  background: var(--col-bg);
  padding: 2.5rem 1.5rem;
}

.privacy-card {
  max-width: 720px;
  margin: 0 auto;
  background: var(--col-surface);
  border: 1px solid var(--col-border);
  border-radius: 14px;
  padding: 2.5rem;
  box-shadow: 0 4px 16px color-mix(in srgb, var(--col-text) 6%, transparent),
              0 16px 48px color-mix(in srgb, var(--col-text) 8%, transparent);
}

.privacy-title {
  font-size: 1.75rem;
  font-weight: 700;
  color: var(--col-text);
  margin: 0 0 0.25rem;
}

.privacy-updated {
  font-size: 0.8rem;
  color: var(--col-subtle);
  margin: 0 0 2rem;
}

.privacy-section {
  margin-bottom: 2rem;
}

.section-heading {
  font-size: 1.0625rem;
  font-weight: 600;
  color: var(--col-text);
  margin: 0 0 0.75rem;
  padding-bottom: 0.375rem;
  border-bottom: 1px solid var(--col-border);
}

.privacy-section p {
  font-size: 0.9rem;
  color: var(--col-muted);
  line-height: 1.7;
  margin: 0 0 0.75rem;
}
.privacy-section p:last-child { margin-bottom: 0; }

.privacy-note {
  font-size: 0.8125rem !important;
  color: var(--col-subtle) !important;
  font-style: italic;
}

.privacy-list {
  list-style: disc;
  padding-left: 1.25rem;
  margin: 0;
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}
.privacy-list li {
  font-size: 0.9rem;
  color: var(--col-muted);
  line-height: 1.6;
}

.data-table {
  width: 100%;
  border-collapse: collapse;
  font-size: 0.875rem;
  margin-bottom: 0.75rem;
}
.data-table th {
  text-align: left;
  padding: 0.5rem 0.75rem;
  font-size: 0.75rem;
  font-weight: 600;
  color: var(--col-subtle);
  text-transform: uppercase;
  letter-spacing: 0.05em;
  background: var(--col-raised);
  border-bottom: 1px solid var(--col-border);
}
.data-table td {
  padding: 0.5rem 0.75rem;
  color: var(--col-muted);
  border-bottom: 1px solid var(--col-border-lt);
  vertical-align: top;
}
.data-table td:first-child { color: var(--col-text); font-weight: 500; white-space: nowrap; }
.data-table tr:last-child td { border-bottom: none; }

.privacy-link {
  color: var(--col-accent);
  text-decoration: none;
}
.privacy-link:hover { text-decoration: underline; }

code {
  font-family: ui-monospace, monospace;
  font-size: 0.85em;
  background: var(--col-raised);
  padding: 0.1em 0.35em;
  border-radius: 3px;
  color: var(--col-text);
}
</style>
